# .spectral.yaml
extends: "@ibm-cloud/openapi-ruleset"
rules:
  # Turn off a rule that is on in the default ruleset
  response-error-response-schema: off
  property-case-convention: off
  schema-description: off
  openapi-tags: off
  response-example-provided: off
