version: '3.8'

services:
  ui:
    container_name: apihome_ui
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.ui
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    depends_on:
      - backend
  backend:
    container_name: apihome_backend
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.backend
    command: gunicorn --bind 0.0.0.0:5000 app:app --log-level debug --timeout 120 -w 1
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
    user: "${UID}:${GID}"  
    volumes:
      - ./mount_volumes/apihome_logs:/home/dockerdev/apihome/logs
  db:
    container_name: apihome_db
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.db
    env_file:
      - ./.env
    ports:
      - "5432:5432"  
    user: "${UID}:${GID}"  
    volumes:
      - ./mount_volumes/pgdata:/var/lib/postgresql/data
