FROM node:16.14.0 as build

WORKDIR /app
COPY  ./ui/src ./src
COPY  ./ui/public ./public
COPY  ./ui/scripts ./scripts
COPY  ./ui/config ./config
COPY  ./ui/package.json  ./

RUN npm install
RUN npm run build

# Setup nginx
FROM nginx:1.15
COPY --from=build /app/build /usr/share/nginx/html
COPY ./docker/nginx/apihq.nginx /etc/nginx/sites-available/apihq.nginx
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/proxy_params /etc/nginx/proxy_params
RUN mkdir -p /etc/nginx/sites-enabled
RUN ln -s /etc/nginx/sites-available/apihq.nginx /etc/nginx/sites-enabled/apihq.nginx

CMD ["nginx", "-g", "daemon off;"]
