version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    command: bash -c "nginx -g "daemon off;" && gunicorn --bind 127.0.0.1:5000 app:app --log-level debug --timeout 90 -w 1"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    depends_on:
      - db
    user: "${UID}:${GID}"  
  db:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.db
    volumes:
      - ./mount_volumes/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"  
    user: "${UID}:${GID}"  