# Build file from inside docker folder
FROM apihq_base:latest as builder

# Add new user
RUN useradd -ms /bin/bash dockerdev && usermod -aG sudo dockerdev
RUN echo 'dockerdev:dockerdev' | chpasswd
RUN chown -R dockerdev:dockerdev /home/dockerdev

# Change current user
USER dockerdev
RUN mkdir /home/dockerdev/apihq
# Create dirs 
RUN mkdir /home/dockerdev/apihq/ui
RUN mkdir /home/dockerdev/apihq/logs

# Copy UI files
FROM builder as build-step1
WORKDIR /home/dockerdev/apihq/ui
COPY --chown=dockerdev:dockerdev ./ui/src ./src
COPY --chown=dockerdev:dockerdev ./ui/public ./public
COPY --chown=dockerdev:dockerdev ./ui/scripts ./scripts
COPY --chown=dockerdev:dockerdev ./ui/config ./config
COPY --chown=dockerdev:dockerdev ./ui/package.json ./ui/package-lock.json ./
RUN npm install
RUN npm run build

# Copy Backend files
WORKDIR /home/dockerdev/apihq
COPY --chown=dockerdev:dockerdev ./app.py ./
COPY --chown=dockerdev:dockerdev ./config.py ./
COPY --chown=dockerdev:dockerdev ./requirements.txt ./
COPY --chown=dockerdev:dockerdev ./.spectral.yaml ./
COPY --chown=dockerdev:dockerdev ./.validaterc ./
COPY --chown=dockerdev:dockerdev ./docker/.env ./
COPY --chown=dockerdev:dockerdev ./backend ./backend
COPY --chown=dockerdev:dockerdev ./crawler ./crawler

# Setup python backend
RUN pip install -r requirements.txt

USER root
# Setup nginx
RUN apt-get install nginx -y
RUN apt-get install wget -y
RUN apt-get install gunicorn -y
RUN apt-get install net-tools -y
FROM build-step1 as build-step2
COPY --from=build-step1 /home/dockerdev/apihq/ui/build /usr/share/nginx/html
COPY ./deploy/apihq.nginx /etc/nginx/conf.d/default.conf
COPY ./deploy/apihq.nginx /etc/nginx/sites-available/apihq.nginx
RUN ln -s /etc/nginx/sites-available/apihq.nginx /etc/nginx/sites-enabled/apihq.nginx

# Setup ZAP
RUN wget -q -O - https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz | tar zxf - -C /opt
RUN ln -s /opt/ZAP_2.11.0 /opt/zaproxy

# Change current user to
USER dockerdev

# Expose Port for Application
EXPOSE 80 443