version: '3.8'

services:
  ui:
    image: sgshanks/apihome:ui
    container_name: apihome_ui
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    depends_on:
      - backend
    volumes:
      - ./volumes/web/certbot/certificates:/etc/nginx/ssl:ro
      - ./volumes/web/logs:/var/log/nginx
  backend:
    image: sgshanks/apihome:backend
    container_name: apihome_backend
    command: gunicorn --bind 0.0.0.0:5000 app:app --log-level debug --timeout 120 -w 1
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
    user: "${UID}:${GID}"  
    volumes:
      - ./volumes/app/logs:/home/dockerdev/apihome/logs
  db:
    image: sgshanks/apihome:db
    container_name: apihome_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"  
    user: "${UID}:${GID}"  
    volumes:
      - ./volumes/db/pgdata:/var/lib/postgresql/data
